# Generated by Django 4.2.2 on 2023-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_page_description_alter_page_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
